"""Make nullabe attr Order

Revision ID: 075e96c151fc
Revises: 2c28b60b2eb7
Create Date: 2024-12-22 14:54:33.763609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075e96c151fc'
down_revision: Union[str, None] = '2c28b60b2eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'administrator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'customer_car_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'customer_car_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'administrator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
