"""Add cascade order-service

Revision ID: 284fa42356e9
Revises: d21aff1da188
Create Date: 2024-12-16 15:16:23.633995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '284fa42356e9'
down_revision: Union[str, None] = 'd21aff1da188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_order_service_service_id_services', 'order_service', type_='foreignkey')
    op.drop_constraint('fk_order_service_order_id_orders', 'order_service', type_='foreignkey')
    op.create_foreign_key(op.f('fk_order_service_service_id_services'), 'order_service', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_order_service_order_id_orders'), 'order_service', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_order_service_order_id_orders'), 'order_service', type_='foreignkey')
    op.drop_constraint(op.f('fk_order_service_service_id_services'), 'order_service', type_='foreignkey')
    op.create_foreign_key('fk_order_service_order_id_orders', 'order_service', 'orders', ['order_id'], ['id'])
    op.create_foreign_key('fk_order_service_service_id_services', 'order_service', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###
