"""Add cascade relationships

Revision ID: d21aff1da188
Revises: fb985eb357af
Create Date: 2024-12-08 20:25:53.744862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21aff1da188'
down_revision: Union[str, None] = 'fb985eb357af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_cars_brand_id_brands', 'cars', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cars_brand_id_brands'), 'cars', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_customer_cars_car_id_cars', 'customer_cars', type_='foreignkey')
    op.drop_constraint('fk_customer_cars_customer_id_users', 'customer_cars', type_='foreignkey')
    op.create_foreign_key(op.f('fk_customer_cars_car_id_cars'), 'customer_cars', 'cars', ['car_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_customer_cars_customer_id_users'), 'customer_cars', 'users', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_orders_employee_id_users', 'orders', type_='foreignkey')
    op.drop_constraint('fk_orders_customer_car_id_customer_cars', 'orders', type_='foreignkey')
    op.drop_constraint('fk_orders_administrator_id_users', 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_employee_id_users'), 'orders', 'users', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_orders_customer_car_id_customer_cars'), 'orders', 'customer_cars', ['customer_car_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_orders_administrator_id_users'), 'orders', 'users', ['administrator_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_role_user_role_id_roles', 'role_user', type_='foreignkey')
    op.drop_constraint('fk_role_user_user_id_users', 'role_user', type_='foreignkey')
    op.create_foreign_key(op.f('fk_role_user_role_id_roles'), 'role_user', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_role_user_user_id_users'), 'role_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_role_user_user_id_users'), 'role_user', type_='foreignkey')
    op.drop_constraint(op.f('fk_role_user_role_id_roles'), 'role_user', type_='foreignkey')
    op.create_foreign_key('fk_role_user_user_id_users', 'role_user', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_role_user_role_id_roles', 'role_user', 'roles', ['role_id'], ['id'])
    op.drop_constraint(op.f('fk_orders_administrator_id_users'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('fk_orders_customer_car_id_customer_cars'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('fk_orders_employee_id_users'), 'orders', type_='foreignkey')
    op.create_foreign_key('fk_orders_administrator_id_users', 'orders', 'users', ['administrator_id'], ['id'])
    op.create_foreign_key('fk_orders_customer_car_id_customer_cars', 'orders', 'customer_cars', ['customer_car_id'], ['id'])
    op.create_foreign_key('fk_orders_employee_id_users', 'orders', 'users', ['employee_id'], ['id'])
    op.drop_constraint(op.f('fk_customer_cars_customer_id_users'), 'customer_cars', type_='foreignkey')
    op.drop_constraint(op.f('fk_customer_cars_car_id_cars'), 'customer_cars', type_='foreignkey')
    op.create_foreign_key('fk_customer_cars_customer_id_users', 'customer_cars', 'users', ['customer_id'], ['id'])
    op.create_foreign_key('fk_customer_cars_car_id_cars', 'customer_cars', 'cars', ['car_id'], ['id'])
    op.drop_constraint(op.f('fk_cars_brand_id_brands'), 'cars', type_='foreignkey')
    op.create_foreign_key('fk_cars_brand_id_brands', 'cars', 'brands', ['brand_id'], ['id'])
    # ### end Alembic commands ###
