[tool.poetry]
name = "library"
version = "0.1.0"
description = ""
authors = ["Wereker <werkermatvey@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.1.5"
pillow = "^11.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
